name: Check for Non-ASCII Characters

on:
  push:
  pull_request:

jobs:
  check-non-ascii:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Search for non-ASCII characters in .py files
        run: |
          has_bad_chars=0
          for file in $(git ls-files '*.py'); do
            if LC_ALL=C grep -n '[^ -~]' "$file"; then
              echo "❌ Found non-ASCII characters in: $file"
              has_bad_chars=1
            fi
          done

          if [ $has_bad_chars -eq 1 ]; then
            echo "❌ Non-ASCII characters detected. Please remove or replace them."
            exit 1
          else
            echo "✅ All files contain only ASCII characters."
          fi
